return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "json",
      "html",
      "diff",
      "dockerfile",
      "javascript",
      "lua",
      "luadoc",
      "latex",
      "gitignore",
      "graphql",
      "go",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "toml",
      "tsx",
      "properties",
      "sql",
      "typescript",
      "vim",
      "yaml",
    },
  },
}
