format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "fg:#7fb4ca" # springBlue

[character]
success_symbol = "[❯](fg:#e0af68)"  # springYellow
error_symbol = "[❯](fg:#fg:d27e99)" # sakuraPink
vimcmd_symbol = "[❮](fg:#dcd7ba)"   # foam

[git_branch]
format = "[$branch]($fg:#e0af68)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "fg:#e0af68"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "fg:#1f1f28"

[cmd_duration]
format = "[$duration]($style) "
style = "fg:#e0af68"

[python]
format = "[$virtualenv]($style) "
style = "fg:#dcd7ba"
